apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/imeredith/new-jx-quickstart:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/imeredith/new-jx-quickstart:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: new-jx-quickstart
        chartPath: charts/new-jx-quickstart
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/imeredith/new-jx-quickstart'
          image.tag: '{{.DIGEST_HEX}}'
